import './vendor/bootstrap5/bootstrap.bundle.min.js';
import './vendor/bootstrap5/bootstrap.min.css';
import './scss/main.scss';
import './js/main.js';
import './images/google-plus.svg';
import './images/pinterest.svg';
import './images/rss.svg';
import './images/twitter.svg';
import './images/slider-image.jpg';