import './vendor/bootstrap5/bootstrap.bundle.min.js';
import './vendor/bootstrap5/bootstrap.min.css';
import './vendor/OwlCarousel2-2.3.4/dist/owl.carousel.js';
import './vendor/OwlCarousel2-2.3.4/dist/assets/owl.carousel.min.css';
import './scss/main.scss';
import './js/main.js';
import './images/google-plus.svg';
import './images/pinterest.svg';
import './images/rss.svg';
import './images/twitter.svg';
import './images/slider-image.jpg';
import './images/image-48x48.jpg';
import './blocks/carousel-mini/js/carousel-mini.js';
import './images/image-225x125.jpg';
import './images/arrow-top.png';
import icon from './images/icons/favicon.ico';
import icon16 from './images/icons/favicon-16x16.png';
import icon32 from './images/icons/favicon-32x32.png';
import icon96 from './images/icons/favicon-96x96.png';
import icon120 from './images/icons/favicon-120x120.png';
import icon192 from './images/icons/favicon-192x192.png';